version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: soat_veiculo_db
    volumes:
      - mongo_db:/data/db
    ports:
      - '6000:27017'
    networks:
      - soat_veiculo_net
    restart: always

  mongodb-express:
    image: mongo-express
    container_name: mongodb-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - soat_veiculo_net
    links:
      - mongodb
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/

  soat-veiculos:
    build: ../soat-veiculos
    image: soat-veiculos/python:25.09    
    container_name: soat-veiculos
    restart: always
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    working_dir: /app
    ports:
      - 8000:8000
    networks:
      - soat_veiculo_net
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ../soat-veiculos/app:/app
      - ../soat-veiculos/app/app-config-prod.json:/app/app-config.json
    tty: true  
    command: >
      bash -c "
      python -u main.py
      && /bin/bash"

  soat-compradores:
    build: ../soat-compradores
    image: soat-compradoress/python:25.09    
    container_name: soat-compradores
    restart: always
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    working_dir: /app
    ports:
      - 8001:8001
    networks:
      - soat_veiculo_net
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ../soat-compradores/app:/app
      - ../soat-compradores/app/app-config-prod.json:/app/app-config.json
    tty: true  
    command: >
      bash -c "
      python -u main.py
      && /bin/bash"

  soat-pagamentos:
    build: ../soat-pagamentos
    image: soat-pagamentos/python:25.09    
    container_name: soat-pagamentos
    restart: always
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    working_dir: /app
    ports:
      - 8002:8002
    networks:
      - soat_veiculo_net
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ../soat-pagamentos/app:/app
      - ../soat-pagamentos/app/app-config-prod.json:/app/app-config.json
    tty: true  
    command: >
      bash -c "
      python -u main.py
      && /bin/bash"

  soat-vendas:
    build: ../soat-vendas
    image: soat-vendas/python:25.09    
    container_name: soat-vendas
    restart: always
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    working_dir: /app
    ports:
      - 8003:8003
    networks:
      - soat_veiculo_net
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ../soat-vendas/app:/app
      - ../soat-vendas/app/app-config-prod.json:/app/app-config.json
    tty: true  
    command: >
      bash -c "
      python -u main.py
      && /bin/bash"


volumes:
  mongo_db:

networks:
  soat_veiculo_net:
    driver: bridge
